### ISSUE TITLE
int32 overflow deserializing generated models

### ISSUE THREAD

**Issue by martincostello** [octokit/dotnet-sdk#95]
Looks like this also affects the new .NET SDK too:

```console
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Int32. Path: $ | LineNumber: 0 | BytePositionInLine: 10.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.GetIntValue()
   at GitHub.Models.EnvironmentObject.<GetFieldDeserializers>b__42_3(IParseNode n)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.AssignFieldValues[T](T item)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.GetObjectValue[T](ParsableFactory`1 factory)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.<GetCollectionOfObjectValues>d__19`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitHub.Repos.Item.Item.Environments.EnvironmentsGetResponse.<GetFieldDeserializers>b__14_0(IParseNode n)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.AssignFieldValues[T](T item)
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.GetObjectValue[T](ParsableFactory`1 factory)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at GitHub.Repos.Item.Item.Environments.EnvironmentsRequestBuilder.<GetAsync>d__4.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
```

_Originally posted by @martincostello in https://github.com/octokit/octokit.net/issues/2893#issuecomment-2172718776_

**Comment by martincostello** [comment]
I'm still seeing this with `0.0.20` of GitHub.Octokit.SDK. Have created a new issue here as the original issue is resolved.

**Comment by kfcampbell** [comment]
Thanks for reporting! This _should_ be fixed as of [v0.0.21](https://github.com/octokit/dotnet-sdk/releases/tag/v0.0.21). Please let us know if you run into any cases where this isn't true! I'm going to close this issue for now, though please don't hesitate to report future occurrences.

**Comment by martincostello** [comment]
@kfcampbell Sorry, it's still broken. Looks like the exact property I have an issue with escaped the changes:

https://github.com/octokit/dotnet-sdk/blob/e4bb0f0bf57a34ed2fcc8b9911c5eb536e90a650/src/GitHub/Models/EnvironmentObject.cs#L34
